### PR TITLE
Remi dev

### PR DESCRIPTION
**Pull request by Remi-Gau**
This should hopefully fix issue #26 and maybe #31 

I relied on spm functions for file selection: it is usually quite robust as to the OS used so that should fix the file separator issues.

I also moved some hard coded variables in the base cvManovaTest file so they will be declared even if some other parts of the pipelines are not run.

### CODE REVIEW

**Comment by charujing** [comment]
Hi Remi Gau, 
Thank you very much.
I have downloaded cvmanova-remi-dev. It's working for regions of interest analysis. Great. However, for cvManovaSearchlight, it echo some errors: This is outputs when i ran cvManovaTest.m.
>> cvManovaTest
analyzing data of subj1 from Haxby et al. (2001)


cvManovaRegion

loading data
 via subj1\model\SPM.mat
 27638 in-mask voxels
  572 in-mask voxels in region 1
  9 in-mask voxels in region 2
  163 in-mask voxels in region 3
 572 in-mask voxels in regions
 reading images
  from D:\program\matlab2018a\bin\subj1\rbold.nii,????
  100 of 1452 volumes loaded
  200 of 1452 volumes loaded
  300 of 1452 volumes loaded
  400 of 1452 volumes loaded
  500 of 1452 volumes loaded
  600 of 1452 volumes loaded
  700 of 1452 volumes loaded
  800 of 1452 volumes loaded
  900 of 1452 volumes loaded
  1000 of 1452 volumes loaded
  1100 of 1452 volumes loaded
  1200 of 1452 volumes loaded
  1300 of 1452 volumes loaded
  1400 of 1452 volumes loaded
  1452 of 1452 volumes loaded
 whitening
 high-pass-filtering
 df: 1452 - 48 - 180 = 1224   [SPM: trRV = 1224  erdf = 1224]

computing cross-validated MANOVA on region


cvManovaSearchlight

loading data
 via subj1\model\SPM.mat
 27638 in-mask voxels
 no region mask
 reading images
  from D:\program\matlab2018a\bin\subj1\rbold.nii,????
  100 of 1452 volumes loaded
  200 of 1452 volumes loaded
  300 of 1452 volumes loaded
  400 of 1452 volumes loaded
  500 of 1452 volumes loaded
  600 of 1452 volumes loaded
  700 of 1452 volumes loaded
  800 of 1452 volumes loaded
  900 of 1452 volumes loaded
  1000 of 1452 volumes loaded
  1100 of 1452 volumes loaded
  1200 of 1452 volumes loaded
  1300 of 1452 volumes loaded
  1400 of 1452 volumes loaded
  1452 of 1452 volumes loaded
 whitening
 high-pass-filtering
 df: 1452 - 48 - 180 = 1224   [SPM: trRV = 1224  erdf = 1224]
错误使用 fletcher16 (line 22)
invalid data!

出错 cvManovaSearchlight (line 60)
uid = dec2hex(fletcher16(uid), 4);

出错 cvManovaTest (line 65)
cvManovaSearchlight(modelDir, 3, Cs)

**Comment by Remi-Gau** [comment]
I don't think that this error is due to the code.

Try setting a breakpoint at line 60 of  `cvManovaSearchlight` and check the content of the `uid` when you are there.

**Comment by charujing** [comment]
Hi, the line 60 could not be run and it did not echo value for the uid. it just echo
K>> uid = dec2hex(fletcher16(uid), 4)
错误使用 fletcher16 (line 22)
invalid data!

**Comment by charujing** [comment]
The uid is "%%val = {       'SPM.mat of 21-8月-2019 17:47:30'       3       {       [1 0 0 0 0 0 0       -1 1 0 0 0 0 0       0 -1 1 0 0 0 0       0 0 -1 1 0 0 0       0 0 0 -1 1 0 0       0 0 0 0 -1 1 0       0 0 0 0 0 -1 1       0 0 0 0 0 0 -1]       [0 0 0       0 0 0       0 0 0       1 0 0       -1 1 0       0 -1 1       0 0 -1       0 0 0]       }'       false       0       }';%%" when it ran after line 58 (before line 60).

**Comment by Remi-Gau** [comment]
I suspect that `fletcher16.m` does not like the `月` character.

I suspect that this a language issue in the way matllab returns dates: if you often get some non ascii characters I suspect this will be a recurrent problem. 

Maybe try switching matlab to english. Not sure how to do that though.

**Comment by charujing** [comment]
Hi Remi
Great. That's the reason. It's working now.
Thanks for your help.

**Comment by Remi-Gau** [comment]
Glad it worked.

Will let @allefeld merge this PR if he wants to. :-)

**Pull request merged**
